[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "programs/solana-itus"
]

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "anchor test --provider.cluster devnet"

[features]
seeds = true

[test]
upgradeable = true
startup_wait = 10000

[[test.genesis]]
address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
program = "dex.so"

[[test.genesis]]
address = "22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD"
program = "swap.so"
upgradeable = true

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "7NL2qWArf2BbEBBH1vTRZCsoNqFATTddH6h8GkVvrLpG"

[[test.validator.clone]]
address = "2RaN5auQwMdg5efgCaVqpETBV8sacWGR8tkK4m9kjo5r"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[programs.devnet]
solana_itus = "2Mwjugz5ULsLFiArfw6d1xHrGnuCfzW3CXor2x9SBziB"